# Generated by Django 3.2.15 on 2023-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230306_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Обрабатывается'), ('packing', 'Упаковывается'), ('delivery', 'Передан в доставку'), ('done', 'Выполнен')], db_index=True, default='Обрабатывается', max_length=50, verbose_name='Статус'),
        ),
    ]
